#!/usr/bin/env ts-node
import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const root = process.cwd();
const checklistPath = join(root, 'planning/overhaul/overhaul-checklist.md');
const outPath = join(root, 'docs', 'roadmap.md');

function extractSections(md: string): string {
  const header = '# Locus Roadmap\n\n(Autogenerated from overhaul-checklist.md; do not edit manually)\n\n';
  // Include only top-level sections and tasks (strip completed lines if desired?) Keep as-is for transparency.
  return header + md;
}

try {
  const src = readFileSync(checklistPath, 'utf8');
  const rendered = extractSections(src);
  writeFileSync(outPath, rendered);
  process.stdout.write('[locus][roadmap] generated docs/roadmap.md\n');
} catch (e:any) {
  process.stderr.write('[locus][roadmap] failed: ' + (e?.message||e) + '\n');
  process.exit(1);
}
