import { GeneratorStep } from '../pipeline';
import { generateCssVariables } from '../theme';
import { withHeader } from '../outputs';

export const themeStep: GeneratorStep = {
  name: 'theme',
  run(ctx) {
    if (ctx.options.includeTheme === false) return;
    const css = withHeader(generateCssVariables(ctx.unified.designSystem), 'theme css');
    const fixed = css.replace(/^\/\/ AUTO-GENERATED[^\n]*\n/, '/* AUTO-GENERATED by Locus. DO NOT EDIT. (theme css) */\n');
    ctx.files['theme.css'] = fixed;
  }
};
