import { GeneratorStep } from '../pipeline';
import { generateNextApp } from '../next';

export const nextStep: GeneratorStep = {
  name: 'next',
  run(ctx) {
    if (ctx.options.includeNext === false) return;
    if (!ctx.meta.hasPages) return;
    const nextFiles = generateNextApp(ctx.unified.pages as any);
    for (const [rel, content] of Object.entries(nextFiles)) {
      if (rel === 'next-app/app/globals.css') {
        const cssHeader = '/* AUTO-GENERATED by Locus. DO NOT EDIT. (next) */\n';
        ctx.files[rel] = (content as string).startsWith('/* AUTO-GENERATED') ? content as string : cssHeader + content;
      } else {
        ctx.addFile(rel, content as string, 'next');
      }
    }
    if (ctx.files['theme.css']) ctx.files['next-app/public/theme.css'] = ctx.files['theme.css'];
  }
};
